USE DB_PROCESSADORA
GO

PRINT 'CRIANDO TABELAS PARA O SITE EMISSOR DE PROPOSTAS'

----
-- TBL_CARTAO_PJ_CANAL
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_CANAL')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_CANAL'
  DROP TABLE TBL_CARTAO_PJ_CANAL
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_CANAL'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_CANAL] (
	[CD_CANAL] [int] IDENTITY(1,1) PRIMARY KEY,
	[DS_CANAL] [varchar](20) NOT NULL,
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_PERFIL
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_PERFIL')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_PERFIL'
  DROP TABLE TBL_CARTAO_PJ_PERFIL
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_PERFIL'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_PERFIL] (
	[CD_PERFIL] [int] IDENTITY(1,1) PRIMARY KEY,
	[CD_CANAL] [int] NOT NULL,
	[DS_PERFIL] [varchar](60) NOT NULL,
	CONSTRAINT [FK_CARTAO_PJ_CANAL_CARTAO_PJ_PERFIL] FOREIGN KEY ([CD_CANAL]) REFERENCES [dbo].[TBL_CARTAO_PJ_CANAL]([CD_CANAL])
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_USUARIO
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_USUARIO')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_USUARIO'
  DROP TABLE TBL_CARTAO_PJ_USUARIO
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_USUARIO'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_USUARIO] (
	[CD_USUARIO] [int] IDENTITY(1,1) PRIMARY KEY,
	[NM_NOME] [varchar](60) NOT NULL,
	[NR_CPF] [numeric](11, 0) NOT NULL,
	[DT_DATA_NASCIMENTO] [datetime] NOT NULL, 
	[NR_DDD] varchar(3) NOT NULL,
	[NR_TELEFONE] varchar(9) NOT NULL,
	[DS_USUARIO] varchar(60) NOT NULL,
	[DS_SENHA] varchar(60) NOT NULL,
	[FL_SITUACAO] char(1) NOT NULL DEFAULT '0',
	[DT_ALTERACAO] datetime NOT NULL,
	[CD_USUARIO_ALTERACAO] int NOT NULL, 
	[CD_PERFIL] int NOT NULL,
	CONSTRAINT [FK_CARTAO_PJ_PERFIL_CARTAO_PJ_USUARIO] FOREIGN KEY ([CD_PERFIL]) REFERENCES [dbo].[TBL_CARTAO_PJ_PERFIL]([CD_PERFIL]),
	CONSTRAINT [FK_CARTAO_PJ_USUARIO_CARTAO_PJ_USUARIO] FOREIGN KEY ([CD_USUARIO]) REFERENCES [dbo].[TBL_CARTAO_PJ_USUARIO]([CD_USUARIO])
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_ENDERECO
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_ENDERECO')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_ENDERECO'
  DROP TABLE TBL_CARTAO_PJ_ENDERECO
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_ENDERECO'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_ENDERECO] (
    [CD_ENDERECO] [int] IDENTITY(1,1) PRIMARY KEY,
	[NR_CEP] [numeric](8, 0) NOT NULL,
	[DS_ENDERECO] [varchar](25) NOT NULL,
	[NR_ENDERECO] [numeric](5, 0) NULL,
	[DS_COMPLEMENTO] [varchar](10) NULL,
	[DS_BAIRRO] [varchar](20) NOT NULL,
	[DS_UF] [varchar](3) NOT NULL,
	[DS_CIDADE] [varchar](22) NOT NULL
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_CLIENTE
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_CLIENTE')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_CLIENTE'
  DROP TABLE TBL_CARTAO_PJ_CLIENTE
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_CLIENTE'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_CLIENTE] (
    [CD_CLIENTE] [int] IDENTITY(1,1) PRIMARY KEY,
	[CD_ENDERECO_SEDE] [int] NOT NULL,
	[CD_ENDERECO_CORREPONDENCIA] [int] NOT NULL,
	[NR_CNPJ] [varchar](14) NOT NULL,
	[NM_RAZAO_SOCIAL] [varchar](60) NOT NULL,
	[DT_DATA_CONSTITUICAO] [datetime] NOT NULL,
	[NR_CNAE] [numeric](7, 0) NOT NULL,
	[NM_NOME_FANTASIA] [varchar](60) NULL,
	[CD_RAMO_ATIVIDADE] [int] NULL,
	[CD_CONTROLE_ACIONARIO] [int] NULL,
	[VL_FATURAMENTO_MENSAL] [numeric](16, 2) NOT NULL,
	[CD_DIA_VENCIMENTO] [int] NULL,
	[NR_TELEFONE_COMERCIAL] [varchar](11) NULL,
	[DS_EMAIL] [varchar](60) NULL,
	[CD_USUARIO_CADASTRO] [int] NOT NULL,
	CONSTRAINT [FK_CARTAO_PJ_ENDERECO_CARTAO_PJ_CLIENTE_SED] FOREIGN KEY ([CD_ENDERECO_SEDE]) REFERENCES [dbo].[TBL_CARTAO_PJ_ENDERECO]([CD_ENDERECO]),
	CONSTRAINT [FK_CARTAO_PJ_ENDERECO_CARTAO_PJ_CLIENTE_COR] FOREIGN KEY ([CD_ENDERECO_CORREPONDENCIA]) REFERENCES [dbo].[TBL_CARTAO_PJ_ENDERECO]([CD_ENDERECO]),
	CONSTRAINT [FK_CARTAO_PJ_USUARIO_CARTAO_PJ_CLIENTE] FOREIGN KEY ([CD_USUARIO_CADASTRO]) REFERENCES [dbo].[TBL_CARTAO_PJ_USUARIO]([CD_USUARIO])
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_PESSOA
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_PESSOA')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_PESSOA'
  DROP TABLE TBL_CARTAO_PJ_PESSOA
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_PESSOA'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_PESSOA] (
    [CD_PESSOA] [int] IDENTITY(1,1) PRIMARY KEY,
	[NR_CPF] [numeric](11, 0) NOT NULL,
	[NM_NOME] [varchar](60) NOT NULL,
	[DT_DATA_NASCIMENTO] [datetime] NOT NULL, 
	[NM_NOME_MAE] [varchar](60) NOT NULL,
	[TP_SEXO] [char](1) NOT NULL,
	[CD_ESTADO_CIVIL] [int] not NULL, 
	[NR_RG] [varchar](20) NULL,
	[DS_ORGAO_EMISSOR_RG] [varchar](60) NULL,
	[DT_DATA_EMISSAO_RG] [datetime] NULL,
	[NR_TELEFONE_CELULAR] [varchar](11) NULL,
	[NR_TELEFONE_COMERCIAL] [varchar](11) NULL,
	[DS_EMAIL] [varchar](60) NULL,
	[FL_REPRESENTANTE_LEGAL] [char](1) NOT NULL DEFAULT '0',
	[FL_REPRESENTANTE_CARTAO] [char](1) NOT NULL DEFAULT '0',
	[FL_SOCIO] [char](1) NOT NULL DEFAULT '0',
	[FL_PROCURADOR] [char](1) NOT NULL DEFAULT '0',
	[PC_PERCENTUAL_ACIONARIO] [numeric](5, 2) NULL,
	[FL_DEVEDOR_SOLIDARIO] [char](1) NOT NULL DEFAULT '0',
	[FL_PORTADOR] [char](1) NOT NULL DEFAULT '0',
	[FL_AVALISTA] [char](1) NOT NULL DEFAULT '0',
	[NM_NOME_EMBOSSING] [varchar](19) NULL,
	[CD_ENDERECO_RESIDENCIAL] [int] NOT NULL,
	[CD_USUARIO_CADASTRO] [int] NOT NULL,
	CONSTRAINT [FK_CARTAO_PJ_ENDERECO_CARTAO_PJ_PESSOA] FOREIGN KEY ([CD_ENDERECO_RESIDENCIAL]) REFERENCES [dbo].[TBL_CARTAO_PJ_ENDERECO]([CD_ENDERECO]),
	CONSTRAINT [FK_CARTAO_PJ_USUARIO_CARTAO_PJ_PESSOA] FOREIGN KEY ([CD_USUARIO_CADASTRO]) REFERENCES [dbo].[TBL_CARTAO_PJ_USUARIO]([CD_USUARIO])
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_TIPO_SOLICITACAO
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_TIPO_SOLICITACAO')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_TIPO_SOLICITACAO'
  DROP TABLE TBL_CARTAO_PJ_TIPO_SOLICITACAO
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_TIPO_SOLICITACAO'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_TIPO_SOLICITACAO] (
	[CD_TIPO_SOLICITACAO] [int] IDENTITY(1,1) PRIMARY KEY,
	[DS_TIPO_SOLICITACAO] [varchar](60) NOT NULL
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_STATUS_SOLICITACAO
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_STATUS_SOLICITACAO')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_STATUS_SOLICITACAO'
  DROP TABLE TBL_CARTAO_PJ_STATUS_SOLICITACAO
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_STATUS_SOLICITACAO'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_STATUS_SOLICITACAO] (
	[CD_STATUS_SOLICITACAO] [int] IDENTITY(1,1) PRIMARY KEY,
	[DS_STATUS_SOLICITACAO] [varchar](60) NOT NULL,
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_SOLICITACAO
----
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_SOLICITACAO')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_SOLICITACAO'
  DROP TABLE TBL_CARTAO_PJ_SOLICITACAO
 END
GO
PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_SOLICITACAO'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_SOLICITACAO] (
	[CD_SOLICITACAO] [int] IDENTITY(1,1) PRIMARY KEY,
	[CD_TIPO_SOLICITACAO] [int] NOT NULL,
	[CD_CANAL] [int] NOT NULL,
	[CD_STATUS_SOLICITACAO] [int] NOT NULL,
	[CD_LOJA_EMISSORA] [int] NOT NULL,
	[CD_CLIENTE] [int] NOT NULL,
	[DT_EMISSAO] [datetime] NOT NULL,
	[DT_ALTERACAO] [datetime] NULL,
	[FL_UPLOAD_ARQUIVOS] [char](1) NOT NULL DEFAULT '0',
	CONSTRAINT [FK_CARTAO_PJ_TIPO_SOLICITACAO_CARTAO_PJ_SOLICITACAO] FOREIGN KEY ([CD_TIPO_SOLICITACAO]) 
		REFERENCES [dbo].[TBL_CARTAO_PJ_TIPO_SOLICITACAO]([CD_TIPO_SOLICITACAO]),
	CONSTRAINT [FK_CARTAO_PJ_CANAL_CARTAO_PJ_SOLICITACAO] FOREIGN KEY ([CD_CANAL]) 
		REFERENCES [dbo].[TBL_CARTAO_PJ_CANAL]([CD_CANAL]),
	CONSTRAINT [FK TBL_CARTAO_PJ_CLIENTE_CARTAO_PJ_SOLICITACAO] FOREIGN KEY ([CD_CLIENTE])
		REFERENCES [dbo].[TBL_CARTAO_PJ_CLIENTE]([CD_CLIENTE])
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_HISTORICO_PROCESSAMENTO
----

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_HISTORICO_PROCESSAMENTO')
 BEGIN
  PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_HISTORICO_PROCESSAMENTO'
  DROP TABLE TBL_CARTAO_PJ_HISTORICO_PROCESSAMENTO
 END
GO

PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_HISTORICO_PROCESSAMENTO'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_HISTORICO_PROCESSAMENTO] (
	[CD_HISTORICO_PROCESSAMENTO] int IDENTITY(1,1) PRIMARY KEY,
	[CD_SEQUENCIA] INT NOT NULL,
	[CD_SOLICITACAO] INT NOT NULL,
	[DT_DATA_INICIO] DATETIME NOT NULL,
	[DT_DATA_FIM] DATETIME NOT NULL,
	[CD_STATUS_SOLICITACAO] INT NOT NULL,
	[DS_DESCRICAO] varchar(60) NULL,
	[CD_USUARIO_CADASTRO] [int] NOT NULL,
	CONSTRAINT [FK_CARTAO_PJ_SOLICITACAO_CARTAO_PJ_HISTORICO_PROCESSAMENTO] FOREIGN KEY ([CD_SOLICITACAO]) REFERENCES [dbo].[TBL_CARTAO_PJ_SOLICITACAO]([CD_SOLICITACAO]),
	CONSTRAINT [FK_CARTAO_PJ_STATUS_SOLICITACAO_CARTAO_PJ_HISTORICO_PROCESSAMENTO] FOREIGN KEY ([CD_STATUS_SOLICITACAO]) REFERENCES [dbo].[TBL_CARTAO_PJ_STATUS_SOLICITACAO]([CD_STATUS_SOLICITACAO]),
	CONSTRAINT [FK_CARTAO_PJ_USUARIO_CARTAO_PJ_HISTORICO_PROCESSAMENTO] FOREIGN KEY ([CD_USUARIO_CADASTRO]) REFERENCES [dbo].[TBL_CARTAO_PJ_USUARIO]([CD_USUARIO])
) ON [PRIMARY]


----
-- TBL_CARTAO_PJ_PROCESSO
----

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_PROCESSO')
  BEGIN
	PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_PROCESSO'
	DROP TABLE TBL_CARTAO_PJ_PROCESSO
  END
GO

PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_PROCESSO'
CREATE TABLE [].[TBL_CARTAO_PJ_PROCESSO] (
	[CD_PROCESSO] [int] IDENTITY(1, 1) PRIMARY KEY,
	[DS_PROCESSO] [varchar](60) NOT NULL,
	[DT_ALTERACAO] [datetime] NOT NULL
) ON [PRIMARY]
GO

----
-- TBL_CARTAO_PJ_DOCUMENTO
----

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = N'TBL_CARTAO_PJ_DOCUMENTO')
  BEGIN
	PRINT 'EXCLUINDO A TABELA TBL_CARTAO_PJ_DOCUMENTO'
	DROP TABLE TBL_CARTAO_PJ_DOCUMENTO
  END
GO

PRINT 'CRIANDO A TABELA TBL_CARTAO_PJ_DOCUMENTO'
CREATE TABLE [dbo].[TBL_CARTAO_PJ_DOCUMENTO] (
	[CD_DOCUMENTO] [int] IDENTITY(1,1) PRIMARY KEY,
	[CD_PROCESSO] [int] NOT NULL,
	[CD_CDOC] [int] NOT NULL,
	[DS_DOCUMENTO] [varchar](60) NOT NULL,
	[FL_OBRIGATORIO] [char](1) NOT NULL DEFAULT '1'
	[DT_ALTERACAO] [datetime] NOT NULL,
	CONSTRAINT [FK_CARTAO_PJ_PROCESSO_CARTAO_PJ_DOCUMENTO] FOREIGN KEY ([CD_PROCESSO]) REFERENCES [dbo].[TBL_CARTAO_PJ_PROCESSO]([CD_PROCESSO])
) ON [PRIMARY]
GO